dist: xenial
language: ruby
rvm: 2.6.2
env:
  - AR_VERSION=5.2.0
  - AR_VERSION=5.1.0
  - AR_VERSION=5.0.0
  - AR_VERSION=4.2.0
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
