language: ruby
rvm: 2.4.2
gemfile:
  - Gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
env:
  - AR_VERSION=5.2.0
  - AR_VERSION=5.1.0
  - AR_VERSION=5.0.0
  - AR_VERSION=4.2.0
notifications:
  email:
    on_success: never
    on_failure: change
